<?php
/**
 * EnumCalendarTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SmartEventSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Smart Event Open API
 *
 * Smart Event Open API documentation
 *
 * The version of the OpenAPI document: 2.0.16
 * Contact: info@smartevent.pl
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SmartEventSDK;

use PHPUnit\Framework\TestCase;

/**
 * EnumCalendarTypeTest Class Doc Comment
 *
 * @category    Class
 * @description EnumCalendarType
 * @package     SmartEventSDK
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EnumCalendarTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EnumCalendarType"
     */
    public function testEnumCalendarType()
    {
    }
}
