<?php
/**
 * EventsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Smart Event Open API
 *
 * Smart Event Open API documentation
 *
 * OpenAPI spec version: 2.0.8
 * Contact: info@smartevent.pl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.18
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * EventsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EventsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for eventsGet
     *
     * Get Events from the system.
     *
     */
    public function testEventsGet()
    {
    }

    /**
     * Test case for eventsGetByCategoryCode
     *
     * Get events data for specied category code.
     *
     */
    public function testEventsGetByCategoryCode()
    {
    }

    /**
     * Test case for eventsGetByEventCode
     *
     * Get specific event data from the system by event code.
     *
     */
    public function testEventsGetByEventCode()
    {
    }

    /**
     * Test case for eventsGetByEventId
     *
     * Get specific event data from the system by event id.
     *
     */
    public function testEventsGetByEventId()
    {
    }
}
