<?php
/**
 * EventsApi
 * PHP version 7.2
 *
 * @category Class
 * @package  SmartEventSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Smart Event Open API
 *
 * Smart Event Open API documentation
 *
 * The version of the OpenAPI document: 2.0.20
 * Contact: info@smartevent.pl
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SmartEventSDK\Client;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\Psr7\Query;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use SmartEventSDK\ApiException;
use SmartEventSDK\Configuration;
use SmartEventSDK\HeaderSelector;
use SmartEventSDK\ObjectSerializer;

/**
 * EventsApi Class Doc Comment
 *
 * @category Class
 * @package  SmartEventSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EventsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
    * Set the host index
    *
    * @param int $hostIndex Host index (required)
    */
    public function setHostIndex($hostIndex)
    {
        $this->hostIndex = $hostIndex;
    }

    /**
    * Get the host index
    *
    * @return int Host index
    */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
    * @return Configuration
    */
    public function getConfig()
    {
        return $this->config;
    }

    /**
    * Operation eventsCalendarGetByEventId
    *
    * Get specific event calendar by type_extension
    *
    * @param  int $id Recource identificator (required)
    * @param  \SmartEventSDK\Models\EnumCalendarType $calendarType type of calendar (required)
    *
    * @throws \SmartEventSDK\ApiException on non-2xx response
    * @throws \InvalidArgumentException
    * @return void
    */
    public function eventsCalendarGetByEventId($id, $calendarType)
    {
    $this->eventsCalendarGetByEventIdWithHttpInfo($id, $calendarType);
    }

    /**
    * Operation eventsCalendarGetByEventIdWithHttpInfo
    *
    * Get specific event calendar by type_extension
    *
    * @param  int $id Recource identificator (required)
    * @param  \SmartEventSDK\Models\EnumCalendarType $calendarType type of calendar (required)
    *
    * @throws \SmartEventSDK\ApiException on non-2xx response
    * @throws \InvalidArgumentException
    * @return array of null, HTTP status code, HTTP response headers (array of strings)
    */
    public function eventsCalendarGetByEventIdWithHttpInfo($id, $calendarType)
    {
        $request = $this->eventsCalendarGetByEventIdRequest($id, $calendarType);
        $returnType = null;

        $options = $this->createHttpClientOption();
        try {
            $response = $this->client->send($request, $options);
        } catch (RequestException $e) {
            $this->throwApiExceptionFromRequestException($e);
        }

        $statusCode = $response->getStatusCode();

        if ($this->isCorrectResponse($statusCode)) {
            return ObjectSerializer::responseBuilder($response, $returnType);
        }

        switch ($statusCode) {
        }
        $headers = $response ? $response->getHeaders() : [];
        $body = $response ? $response->getBody() : null;
        $responseData = ObjectSerializer::deserialize($body, $returnType, $headers);
        $this->throwApiException($statusCode, $response, $request, null, $responseData);
    }

    /**
    * Operation eventsCalendarGetByEventIdAsync
    *
    * Get specific event calendar by type_extension
    *
    * @param  int $id Recource identificator (required)
    * @param  \SmartEventSDK\Models\EnumCalendarType $calendarType type of calendar (required)
    *
    * @throws \InvalidArgumentException
    * @return \GuzzleHttp\Promise\PromiseInterface
    */
    public function eventsCalendarGetByEventIdAsync($id, $calendarType)
    {
        return $this->eventsCalendarGetByEventIdAsyncWithHttpInfo($id, $calendarType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
    * Operation eventsCalendarGetByEventIdAsyncWithHttpInfo
    *
    * Get specific event calendar by type_extension
    *
    * @param  int $id Recource identificator (required)
    * @param  \SmartEventSDK\Models\EnumCalendarType $calendarType type of calendar (required)
    *
    * @throws \InvalidArgumentException
    * @return \GuzzleHttp\Promise\PromiseInterface
    */
    public function eventsCalendarGetByEventIdAsyncWithHttpInfo($id, $calendarType)
    {
        $returnType = '';
        $request = $this->eventsCalendarGetByEventIdRequest($id, $calendarType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function (ResponseInterface $response) use ($returnType) {
                    return ObjectSerializer::responseBuilder($response, $returnType);
                },
                function (RequestException $exception) {
                    $this->throwApiExceptionFromRequestException($exception);
                }
            );
    }

    /**
    * Create request for operation 'eventsCalendarGetByEventId'
    *
    * @param  int $id Recource identificator (required)
    * @param  \SmartEventSDK\Models\EnumCalendarType $calendarType type of calendar (required)
    *
    * @throws \InvalidArgumentException
    * @return \GuzzleHttp\Psr7\Request
    */
    public function eventsCalendarGetByEventIdRequest($id, $calendarType)
    {
        $this->assertIsNotEmpty($id, 'Missing the required parameter $id when calling eventsCalendarGetByEventId');
        $this->assertIsNotEmpty($calendarType, 'Missing the required parameter $calendarType when calling eventsCalendarGetByEventId');
        $resourcePath = '/events/{id}/calendar/{calendarType}';
        $httpMethod = 'GET';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $isMultipart = false;

        // path params
        if ($id !== null) {
            $resourcePath = str_replace('{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }
        // path params
        if ($calendarType !== null) {
            $resourcePath = str_replace('{' . 'calendarType' . '}',
                ObjectSerializer::toPathValue($calendarType),
                $resourcePath
            );
        }
        if ($isMultipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            $httpBody = $this->buildBody($formParams, $isMultipart, $this->isHeaderContentTypeJson($headers));
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = Query::build($queryParams);
        $query = http_build_query($queryParams);

        return new Request($httpMethod, $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }

    /**
    * Operation eventsGet
    *
    * Get Events from the system
    *
    *
    * @throws \SmartEventSDK\ApiException on non-2xx response
    * @throws \InvalidArgumentException
    * @return \SmartEventSDK\Models\Event[]|\SmartEventSDK\Models\GeneralError
    */
    public function eventsGet()
    {
    list($response) = $this->eventsGetWithHttpInfo();
        return $response;
    }

    /**
    * Operation eventsGetWithHttpInfo
    *
    * Get Events from the system
    *
    *
    * @throws \SmartEventSDK\ApiException on non-2xx response
    * @throws \InvalidArgumentException
    * @return array of \SmartEventSDK\Models\Event[]|\SmartEventSDK\Models\GeneralError, HTTP status code, HTTP response headers (array of strings)
    */
    public function eventsGetWithHttpInfo()
    {
        $request = $this->eventsGetRequest();
        $returnType = '\SmartEventSDK\Models\Event[]';

        $options = $this->createHttpClientOption();
        try {
            $response = $this->client->send($request, $options);
        } catch (RequestException $e) {
            $this->throwApiExceptionFromRequestException($e);
        }

        $statusCode = $response->getStatusCode();

        if ($this->isCorrectResponse($statusCode)) {
            return ObjectSerializer::responseBuilder($response, $returnType);
        }

        switch ($statusCode) {
            case 200:
                $returnType = '\SmartEventSDK\Models\Event[]';
            break;
            case 500:
                $returnType = '\SmartEventSDK\Models\GeneralError';
            break;
        }
        $headers = $response ? $response->getHeaders() : [];
        $body = $response ? $response->getBody() : null;
        $responseData = ObjectSerializer::deserialize($body, $returnType, $headers);
        $this->throwApiException($statusCode, $response, $request, null, $responseData);
    }

    /**
    * Operation eventsGetAsync
    *
    * Get Events from the system
    *
    *
    * @throws \InvalidArgumentException
    * @return \GuzzleHttp\Promise\PromiseInterface
    */
    public function eventsGetAsync()
    {
        return $this->eventsGetAsyncWithHttpInfo()
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
    * Operation eventsGetAsyncWithHttpInfo
    *
    * Get Events from the system
    *
    *
    * @throws \InvalidArgumentException
    * @return \GuzzleHttp\Promise\PromiseInterface
    */
    public function eventsGetAsyncWithHttpInfo()
    {
        $returnType = '\SmartEventSDK\Models\Event[]';
        $request = $this->eventsGetRequest();

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function (ResponseInterface $response) use ($returnType) {
                    return ObjectSerializer::responseBuilder($response, $returnType);
                },
                function (RequestException $exception) {
                    $this->throwApiExceptionFromRequestException($exception);
                }
            );
    }

    /**
    * Create request for operation 'eventsGet'
    *
    *
    * @throws \InvalidArgumentException
    * @return \GuzzleHttp\Psr7\Request
    */
    public function eventsGetRequest()
    {
        $resourcePath = '/events';
        $httpMethod = 'GET';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $isMultipart = false;

        if ($isMultipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            $httpBody = $this->buildBody($formParams, $isMultipart, $this->isHeaderContentTypeJson($headers));
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = Query::build($queryParams);
        $query = http_build_query($queryParams);

        return new Request($httpMethod, $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }

    /**
    * Operation eventsGetByCategoryCode
    *
    * Get events data for specied category code
    *
    * @param  string $code code (required)
    *
    * @throws \SmartEventSDK\ApiException on non-2xx response
    * @throws \InvalidArgumentException
    * @return \SmartEventSDK\Models\Event[]|\SmartEventSDK\Models\GeneralError
    */
    public function eventsGetByCategoryCode($code)
    {
    list($response) = $this->eventsGetByCategoryCodeWithHttpInfo($code);
        return $response;
    }

    /**
    * Operation eventsGetByCategoryCodeWithHttpInfo
    *
    * Get events data for specied category code
    *
    * @param  string $code (required)
    *
    * @throws \SmartEventSDK\ApiException on non-2xx response
    * @throws \InvalidArgumentException
    * @return array of \SmartEventSDK\Models\Event[]|\SmartEventSDK\Models\GeneralError, HTTP status code, HTTP response headers (array of strings)
    */
    public function eventsGetByCategoryCodeWithHttpInfo($code)
    {
        $request = $this->eventsGetByCategoryCodeRequest($code);
        $returnType = '\SmartEventSDK\Models\Event[]';

        $options = $this->createHttpClientOption();
        try {
            $response = $this->client->send($request, $options);
        } catch (RequestException $e) {
            $this->throwApiExceptionFromRequestException($e);
        }

        $statusCode = $response->getStatusCode();

        if ($this->isCorrectResponse($statusCode)) {
            return ObjectSerializer::responseBuilder($response, $returnType);
        }

        switch ($statusCode) {
            case 200:
                $returnType = '\SmartEventSDK\Models\Event[]';
            break;
            case 500:
                $returnType = '\SmartEventSDK\Models\GeneralError';
            break;
        }
        $headers = $response ? $response->getHeaders() : [];
        $body = $response ? $response->getBody() : null;
        $responseData = ObjectSerializer::deserialize($body, $returnType, $headers);
        $this->throwApiException($statusCode, $response, $request, null, $responseData);
    }

    /**
    * Operation eventsGetByCategoryCodeAsync
    *
    * Get events data for specied category code
    *
    * @param  string $code (required)
    *
    * @throws \InvalidArgumentException
    * @return \GuzzleHttp\Promise\PromiseInterface
    */
    public function eventsGetByCategoryCodeAsync($code)
    {
        return $this->eventsGetByCategoryCodeAsyncWithHttpInfo($code)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
    * Operation eventsGetByCategoryCodeAsyncWithHttpInfo
    *
    * Get events data for specied category code
    *
    * @param  string $code (required)
    *
    * @throws \InvalidArgumentException
    * @return \GuzzleHttp\Promise\PromiseInterface
    */
    public function eventsGetByCategoryCodeAsyncWithHttpInfo($code)
    {
        $returnType = '\SmartEventSDK\Models\Event[]';
        $request = $this->eventsGetByCategoryCodeRequest($code);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function (ResponseInterface $response) use ($returnType) {
                    return ObjectSerializer::responseBuilder($response, $returnType);
                },
                function (RequestException $exception) {
                    $this->throwApiExceptionFromRequestException($exception);
                }
            );
    }

    /**
    * Create request for operation 'eventsGetByCategoryCode'
    *
    * @param  string $code (required)
    *
    * @throws \InvalidArgumentException
    * @return \GuzzleHttp\Psr7\Request
    */
    public function eventsGetByCategoryCodeRequest($code)
    {
        $this->assertIsNotEmpty($code, 'Missing the required parameter $code when calling eventsGetByCategoryCode');
        $resourcePath = '/category-events/by-code/{code}';
        $httpMethod = 'GET';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $isMultipart = false;

        // path params
        if ($code !== null) {
            $resourcePath = str_replace('{' . 'code' . '}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }
        if ($isMultipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            $httpBody = $this->buildBody($formParams, $isMultipart, $this->isHeaderContentTypeJson($headers));
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = Query::build($queryParams);
        $query = http_build_query($queryParams);

        return new Request($httpMethod, $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }

    /**
    * Operation eventsGetByEventCode
    *
    * Get specific event data from the system by event code
    *
    * @param  string $code code (required)
    *
    * @throws \SmartEventSDK\ApiException on non-2xx response
    * @throws \InvalidArgumentException
    * @return \SmartEventSDK\Models\Event[]|\SmartEventSDK\Models\GeneralError
    */
    public function eventsGetByEventCode($code)
    {
    list($response) = $this->eventsGetByEventCodeWithHttpInfo($code);
        return $response;
    }

    /**
    * Operation eventsGetByEventCodeWithHttpInfo
    *
    * Get specific event data from the system by event code
    *
    * @param  string $code (required)
    *
    * @throws \SmartEventSDK\ApiException on non-2xx response
    * @throws \InvalidArgumentException
    * @return array of \SmartEventSDK\Models\Event[]|\SmartEventSDK\Models\GeneralError, HTTP status code, HTTP response headers (array of strings)
    */
    public function eventsGetByEventCodeWithHttpInfo($code)
    {
        $request = $this->eventsGetByEventCodeRequest($code);
        $returnType = '\SmartEventSDK\Models\Event[]';

        $options = $this->createHttpClientOption();
        try {
            $response = $this->client->send($request, $options);
        } catch (RequestException $e) {
            $this->throwApiExceptionFromRequestException($e);
        }

        $statusCode = $response->getStatusCode();

        if ($this->isCorrectResponse($statusCode)) {
            return ObjectSerializer::responseBuilder($response, $returnType);
        }

        switch ($statusCode) {
            case 200:
                $returnType = '\SmartEventSDK\Models\Event[]';
            break;
            case 500:
                $returnType = '\SmartEventSDK\Models\GeneralError';
            break;
        }
        $headers = $response ? $response->getHeaders() : [];
        $body = $response ? $response->getBody() : null;
        $responseData = ObjectSerializer::deserialize($body, $returnType, $headers);
        $this->throwApiException($statusCode, $response, $request, null, $responseData);
    }

    /**
    * Operation eventsGetByEventCodeAsync
    *
    * Get specific event data from the system by event code
    *
    * @param  string $code (required)
    *
    * @throws \InvalidArgumentException
    * @return \GuzzleHttp\Promise\PromiseInterface
    */
    public function eventsGetByEventCodeAsync($code)
    {
        return $this->eventsGetByEventCodeAsyncWithHttpInfo($code)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
    * Operation eventsGetByEventCodeAsyncWithHttpInfo
    *
    * Get specific event data from the system by event code
    *
    * @param  string $code (required)
    *
    * @throws \InvalidArgumentException
    * @return \GuzzleHttp\Promise\PromiseInterface
    */
    public function eventsGetByEventCodeAsyncWithHttpInfo($code)
    {
        $returnType = '\SmartEventSDK\Models\Event[]';
        $request = $this->eventsGetByEventCodeRequest($code);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function (ResponseInterface $response) use ($returnType) {
                    return ObjectSerializer::responseBuilder($response, $returnType);
                },
                function (RequestException $exception) {
                    $this->throwApiExceptionFromRequestException($exception);
                }
            );
    }

    /**
    * Create request for operation 'eventsGetByEventCode'
    *
    * @param  string $code (required)
    *
    * @throws \InvalidArgumentException
    * @return \GuzzleHttp\Psr7\Request
    */
    public function eventsGetByEventCodeRequest($code)
    {
        $this->assertIsNotEmpty($code, 'Missing the required parameter $code when calling eventsGetByEventCode');
        $resourcePath = '/events/by-code/{code}';
        $httpMethod = 'GET';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $isMultipart = false;

        // path params
        if ($code !== null) {
            $resourcePath = str_replace('{' . 'code' . '}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }
        if ($isMultipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            $httpBody = $this->buildBody($formParams, $isMultipart, $this->isHeaderContentTypeJson($headers));
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = Query::build($queryParams);
        $query = http_build_query($queryParams);

        return new Request($httpMethod, $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }

    /**
    * Operation eventsGetByEventId
    *
    * Get specific event data from the system by event id
    *
    * @param  int $id Recource identificator (required)
    *
    * @throws \SmartEventSDK\ApiException on non-2xx response
    * @throws \InvalidArgumentException
    * @return \SmartEventSDK\Models\Event[]|\SmartEventSDK\Models\GeneralError
    */
    public function eventsGetByEventId($id)
    {
    list($response) = $this->eventsGetByEventIdWithHttpInfo($id);
        return $response;
    }

    /**
    * Operation eventsGetByEventIdWithHttpInfo
    *
    * Get specific event data from the system by event id
    *
    * @param  int $id Recource identificator (required)
    *
    * @throws \SmartEventSDK\ApiException on non-2xx response
    * @throws \InvalidArgumentException
    * @return array of \SmartEventSDK\Models\Event[]|\SmartEventSDK\Models\GeneralError, HTTP status code, HTTP response headers (array of strings)
    */
    public function eventsGetByEventIdWithHttpInfo($id)
    {
        $request = $this->eventsGetByEventIdRequest($id);
        $returnType = '\SmartEventSDK\Models\Event[]';

        $options = $this->createHttpClientOption();
        try {
            $response = $this->client->send($request, $options);
        } catch (RequestException $e) {
            $this->throwApiExceptionFromRequestException($e);
        }

        $statusCode = $response->getStatusCode();

        if ($this->isCorrectResponse($statusCode)) {
            return ObjectSerializer::responseBuilder($response, $returnType);
        }

        switch ($statusCode) {
            case 200:
                $returnType = '\SmartEventSDK\Models\Event[]';
            break;
            case 500:
                $returnType = '\SmartEventSDK\Models\GeneralError';
            break;
        }
        $headers = $response ? $response->getHeaders() : [];
        $body = $response ? $response->getBody() : null;
        $responseData = ObjectSerializer::deserialize($body, $returnType, $headers);
        $this->throwApiException($statusCode, $response, $request, null, $responseData);
    }

    /**
    * Operation eventsGetByEventIdAsync
    *
    * Get specific event data from the system by event id
    *
    * @param  int $id Recource identificator (required)
    *
    * @throws \InvalidArgumentException
    * @return \GuzzleHttp\Promise\PromiseInterface
    */
    public function eventsGetByEventIdAsync($id)
    {
        return $this->eventsGetByEventIdAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
    * Operation eventsGetByEventIdAsyncWithHttpInfo
    *
    * Get specific event data from the system by event id
    *
    * @param  int $id Recource identificator (required)
    *
    * @throws \InvalidArgumentException
    * @return \GuzzleHttp\Promise\PromiseInterface
    */
    public function eventsGetByEventIdAsyncWithHttpInfo($id)
    {
        $returnType = '\SmartEventSDK\Models\Event[]';
        $request = $this->eventsGetByEventIdRequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function (ResponseInterface $response) use ($returnType) {
                    return ObjectSerializer::responseBuilder($response, $returnType);
                },
                function (RequestException $exception) {
                    $this->throwApiExceptionFromRequestException($exception);
                }
            );
    }

    /**
    * Create request for operation 'eventsGetByEventId'
    *
    * @param  int $id Recource identificator (required)
    *
    * @throws \InvalidArgumentException
    * @return \GuzzleHttp\Psr7\Request
    */
    public function eventsGetByEventIdRequest($id)
    {
        $this->assertIsNotEmpty($id, 'Missing the required parameter $id when calling eventsGetByEventId');
        $resourcePath = '/events/by-id/{id}';
        $httpMethod = 'GET';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $isMultipart = false;

        // path params
        if ($id !== null) {
            $resourcePath = str_replace('{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }
        if ($isMultipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            $httpBody = $this->buildBody($formParams, $isMultipart, $this->isHeaderContentTypeJson($headers));
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = Query::build($queryParams);
        $query = http_build_query($queryParams);

        return new Request($httpMethod, $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }

    /**
    * Operation eventsGetByTicketId
    *
    * Get specific event data from the system by ticket id
    *
    * @param  int $id Recource identificator (required)
    *
    * @throws \SmartEventSDK\ApiException on non-2xx response
    * @throws \InvalidArgumentException
    * @return \SmartEventSDK\Models\Event[]|\SmartEventSDK\Models\GeneralError
    */
    public function eventsGetByTicketId($id)
    {
    list($response) = $this->eventsGetByTicketIdWithHttpInfo($id);
        return $response;
    }

    /**
    * Operation eventsGetByTicketIdWithHttpInfo
    *
    * Get specific event data from the system by ticket id
    *
    * @param  int $id Recource identificator (required)
    *
    * @throws \SmartEventSDK\ApiException on non-2xx response
    * @throws \InvalidArgumentException
    * @return array of \SmartEventSDK\Models\Event[]|\SmartEventSDK\Models\GeneralError, HTTP status code, HTTP response headers (array of strings)
    */
    public function eventsGetByTicketIdWithHttpInfo($id)
    {
        $request = $this->eventsGetByTicketIdRequest($id);
        $returnType = '\SmartEventSDK\Models\Event[]';

        $options = $this->createHttpClientOption();
        try {
            $response = $this->client->send($request, $options);
        } catch (RequestException $e) {
            $this->throwApiExceptionFromRequestException($e);
        }

        $statusCode = $response->getStatusCode();

        if ($this->isCorrectResponse($statusCode)) {
            return ObjectSerializer::responseBuilder($response, $returnType);
        }

        switch ($statusCode) {
            case 200:
                $returnType = '\SmartEventSDK\Models\Event[]';
            break;
            case 500:
                $returnType = '\SmartEventSDK\Models\GeneralError';
            break;
        }
        $headers = $response ? $response->getHeaders() : [];
        $body = $response ? $response->getBody() : null;
        $responseData = ObjectSerializer::deserialize($body, $returnType, $headers);
        $this->throwApiException($statusCode, $response, $request, null, $responseData);
    }

    /**
    * Operation eventsGetByTicketIdAsync
    *
    * Get specific event data from the system by ticket id
    *
    * @param  int $id Recource identificator (required)
    *
    * @throws \InvalidArgumentException
    * @return \GuzzleHttp\Promise\PromiseInterface
    */
    public function eventsGetByTicketIdAsync($id)
    {
        return $this->eventsGetByTicketIdAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
    * Operation eventsGetByTicketIdAsyncWithHttpInfo
    *
    * Get specific event data from the system by ticket id
    *
    * @param  int $id Recource identificator (required)
    *
    * @throws \InvalidArgumentException
    * @return \GuzzleHttp\Promise\PromiseInterface
    */
    public function eventsGetByTicketIdAsyncWithHttpInfo($id)
    {
        $returnType = '\SmartEventSDK\Models\Event[]';
        $request = $this->eventsGetByTicketIdRequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function (ResponseInterface $response) use ($returnType) {
                    return ObjectSerializer::responseBuilder($response, $returnType);
                },
                function (RequestException $exception) {
                    $this->throwApiExceptionFromRequestException($exception);
                }
            );
    }

    /**
    * Create request for operation 'eventsGetByTicketId'
    *
    * @param  int $id Recource identificator (required)
    *
    * @throws \InvalidArgumentException
    * @return \GuzzleHttp\Psr7\Request
    */
    public function eventsGetByTicketIdRequest($id)
    {
        $this->assertIsNotEmpty($id, 'Missing the required parameter $id when calling eventsGetByTicketId');
        $resourcePath = '/events/by-ticket/{id}';
        $httpMethod = 'GET';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $isMultipart = false;

        // path params
        if ($id !== null) {
            $resourcePath = str_replace('{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }
        if ($isMultipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            $httpBody = $this->buildBody($formParams, $isMultipart, $this->isHeaderContentTypeJson($headers));
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = Query::build($queryParams);
        $query = http_build_query($queryParams);

        return new Request($httpMethod, $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }


    /**
    * Create http client option
    *
    * @throws \RuntimeException on file opening failure
    * @return array of http client options
    */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    /**
    * @param RequestException $e
    * @param mixed|null       $responseData
    *
    * @return void
    * @throws ApiException
    */
    private function throwApiExceptionFromRequestException(RequestException $e, $responseData = null): void
    {
        $this->throwApiException((int) $e->getCode(), $e->getResponse(), $e->getRequest(), $e->getMessage(), $responseData);
    }

    /**
    * @param int                    $statusCode
    * @param ResponseInterface|null $response
    * @param RequestInterface|null  $request
    * @param string|null            $message
    * @param mixed|null             $responseData
    *
    * @return void
    * @throws ApiException
    */
    private function throwApiException(
        int $statusCode,
        ?ResponseInterface $response = null,
        ?RequestInterface $request = null,
        ?string $message = null,
        $responseData = null
    ): void
    {
        $message = sprintf('[%d] Error connecting to the API (url: %s) . %s',
            $statusCode,
            ($request) ? $request->getUri() : '',
            $message
        );
        $headers = $response ? $response->getHeaders() : [];
        $body = $response ? $response->getBody() : null;

        $exception = new ApiException($message, $statusCode, $headers, $body);
        $exception->setResponseObject($responseData);

        throw $exception;
    }


    /**
    * @param int $statusCode
    * @return bool
    */
    private function isCorrectResponse(int $statusCode): bool
    {
        return $statusCode >= 200 && $statusCode < 300;
    }

    /**
    * @param $parameter
    * @param string $message
    */
    private function assertIsNotEmpty($parameter, string $message): void
    {
        if ($parameter === null || (is_array($parameter) && count($parameter) === 0)) {
            throw new \InvalidArgumentException($message);
        }
    }

    /**
     * @param $parameter
     * @param string $style
     * @param string $basename
     * @return array
     */
    private function buildQueryParam($parameter, string $style, string $basename): array
    {
        $queryParams = [];
        if('form' === $style && is_array($parameter)) {
            foreach($parameter as $key => $value) {
                $queryParams[$basename][$key] = $value;
            }
        } else {
            $queryParams[$basename] = $parameter;
        }

        return $queryParams;
    }

    /**
    * @param array $formParams
    * @param bool $isMultipart
    * @param bool $isJson
    * @return MultipartStream|string
    */
    private function buildBody(array $formParams, bool $isMultipart, bool $isJson)
    {
        if ($isMultipart) {
            $multipartContents = [];
            foreach ($formParams as $formParamName => $formParamValue) {
                $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                foreach ($formParamValueItems as $formParamValueItem) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValueItem
                    ];
                }
            }
            // for HTTP post (form)
            return new MultipartStream($multipartContents);
        } elseif ($isJson) {
            return \GuzzleHttp\json_encode($formParams);
        } else {
            // for HTTP post (form)
            return \GuzzleHttp\Psr7\build_query($formParams);
        }
    }

    /**
    * @param $headers
    * @return bool
    */
    private function isHeaderContentTypeJson($headers): bool
    {
        return $headers['Content-Type'] === 'application/json';
    }

}
