<?php
/**
 * InvoicesApi
 * PHP version 5
 *
 * @category Class
 * @package  SmartEventSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Smart Event Open API
 *
 * Smart Event Open API documentation
 *
 * The version of the OpenAPI document: 2.0.16
 * Contact: info@smartevent.pl
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SmartEventSDK\Client;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use SmartEventSDK\ApiException;
use SmartEventSDK\Configuration;
use SmartEventSDK\HeaderSelector;
use SmartEventSDK\ObjectSerializer;

/**
 * InvoicesApi Class Doc Comment
 *
 * @category Class
 * @package  SmartEventSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InvoicesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $host_index (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $host_index = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $host_index;
    }

    /**
     * Set the host index
     *
     * @param  int Host index (required)
     */
    public function setHostIndex($host_index)
    {
        $this->hostIndex = $host_index;
    }

    /**
     * Get the host index
     *
     * @return Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation invoicesCreate
     *
     * Create invoice by type
     *
     * @param  string $tokenValue Registration identifier. (required)
     * @param  \SmartEventSDK\Models\EnumInvoiceType $invoiceType type of invoice vat or proforma (required)
     *
     * @throws \SmartEventSDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return string
     */
    public function invoicesCreate($tokenValue, $invoiceType)
    {
        list($response) = $this->invoicesCreateWithHttpInfo($tokenValue, $invoiceType);
        return $response;
    }

    /**
     * Operation invoicesCreateWithHttpInfo
     *
     * Create invoice by type
     *
     * @param  string $tokenValue Registration identifier. (required)
     * @param  \SmartEventSDK\Models\EnumInvoiceType $invoiceType type of invoice vat or proforma (required)
     *
     * @throws \SmartEventSDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of string, HTTP status code, HTTP response headers (array of strings)
     */
    public function invoicesCreateWithHttpInfo($tokenValue, $invoiceType)
    {
        $request = $this->invoicesCreateRequest($tokenValue, $invoiceType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('string' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'string', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'string';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation invoicesCreateAsync
     *
     * Create invoice by type
     *
     * @param  string $tokenValue Registration identifier. (required)
     * @param  \SmartEventSDK\Models\EnumInvoiceType $invoiceType type of invoice vat or proforma (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function invoicesCreateAsync($tokenValue, $invoiceType)
    {
        return $this->invoicesCreateAsyncWithHttpInfo($tokenValue, $invoiceType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation invoicesCreateAsyncWithHttpInfo
     *
     * Create invoice by type
     *
     * @param  string $tokenValue Registration identifier. (required)
     * @param  \SmartEventSDK\Models\EnumInvoiceType $invoiceType type of invoice vat or proforma (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function invoicesCreateAsyncWithHttpInfo($tokenValue, $invoiceType)
    {
        $returnType = 'string';
        $request = $this->invoicesCreateRequest($tokenValue, $invoiceType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'invoicesCreate'
     *
     * @param  string $tokenValue Registration identifier. (required)
     * @param  \SmartEventSDK\Models\EnumInvoiceType $invoiceType type of invoice vat or proforma (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function invoicesCreateRequest($tokenValue, $invoiceType)
    {
        // verify the required parameter 'tokenValue' is set
        if ($tokenValue === null || (is_array($tokenValue) && count($tokenValue) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tokenValue when calling invoicesCreate'
            );
        }
        // verify the required parameter 'invoiceType' is set
        if ($invoiceType === null || (is_array($invoiceType) && count($invoiceType) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $invoiceType when calling invoicesCreate'
            );
        }

        $resourcePath = '/invoices/{invoiceType}/create/{tokenValue}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($tokenValue !== null) {
            $resourcePath = str_replace(
                '{' . 'tokenValue' . '}',
                ObjectSerializer::toPathValue($tokenValue),
                $resourcePath
            );
        }
        // path params
        if ($invoiceType !== null) {
            $resourcePath = str_replace(
                '{' . 'invoiceType' . '}',
                ObjectSerializer::toPathValue($invoiceType),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/pdf']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/pdf'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation invoicesDownload
     *
     * Download invoice by type for order
     *
     * @param  string $tokenValue Registration identifier. (required)
     * @param  \SmartEventSDK\Models\EnumInvoiceType $invoiceType type of invoice vat or proforma (required)
     *
     * @throws \SmartEventSDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return string
     */
    public function invoicesDownload($tokenValue, $invoiceType)
    {
        list($response) = $this->invoicesDownloadWithHttpInfo($tokenValue, $invoiceType);
        return $response;
    }

    /**
     * Operation invoicesDownloadWithHttpInfo
     *
     * Download invoice by type for order
     *
     * @param  string $tokenValue Registration identifier. (required)
     * @param  \SmartEventSDK\Models\EnumInvoiceType $invoiceType type of invoice vat or proforma (required)
     *
     * @throws \SmartEventSDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of string, HTTP status code, HTTP response headers (array of strings)
     */
    public function invoicesDownloadWithHttpInfo($tokenValue, $invoiceType)
    {
        $request = $this->invoicesDownloadRequest($tokenValue, $invoiceType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('string' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'string', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'string';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation invoicesDownloadAsync
     *
     * Download invoice by type for order
     *
     * @param  string $tokenValue Registration identifier. (required)
     * @param  \SmartEventSDK\Models\EnumInvoiceType $invoiceType type of invoice vat or proforma (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function invoicesDownloadAsync($tokenValue, $invoiceType)
    {
        return $this->invoicesDownloadAsyncWithHttpInfo($tokenValue, $invoiceType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation invoicesDownloadAsyncWithHttpInfo
     *
     * Download invoice by type for order
     *
     * @param  string $tokenValue Registration identifier. (required)
     * @param  \SmartEventSDK\Models\EnumInvoiceType $invoiceType type of invoice vat or proforma (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function invoicesDownloadAsyncWithHttpInfo($tokenValue, $invoiceType)
    {
        $returnType = 'string';
        $request = $this->invoicesDownloadRequest($tokenValue, $invoiceType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'invoicesDownload'
     *
     * @param  string $tokenValue Registration identifier. (required)
     * @param  \SmartEventSDK\Models\EnumInvoiceType $invoiceType type of invoice vat or proforma (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function invoicesDownloadRequest($tokenValue, $invoiceType)
    {
        // verify the required parameter 'tokenValue' is set
        if ($tokenValue === null || (is_array($tokenValue) && count($tokenValue) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tokenValue when calling invoicesDownload'
            );
        }
        // verify the required parameter 'invoiceType' is set
        if ($invoiceType === null || (is_array($invoiceType) && count($invoiceType) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $invoiceType when calling invoicesDownload'
            );
        }

        $resourcePath = '/invoices/{invoiceType}/download/{tokenValue}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($tokenValue !== null) {
            $resourcePath = str_replace(
                '{' . 'tokenValue' . '}',
                ObjectSerializer::toPathValue($tokenValue),
                $resourcePath
            );
        }
        // path params
        if ($invoiceType !== null) {
            $resourcePath = str_replace(
                '{' . 'invoiceType' . '}',
                ObjectSerializer::toPathValue($invoiceType),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/pdf']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/pdf'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
